name: OpenAI Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    with:
      repository: ${{github.event.pull_request.head.repo.full_name}}
      ref: ${{github.event.pull_request.head.ref}}
      submodules: false
    # Checkout the repo
    uses: actions/checkout@v3
    with:
    # Repository name with owner.For example, actions/checkout
      Default: ${{ github.repository }}
  # "my_first_job"というジョブIDでジョブを定義
  my_first_job:
    name: My first job
  # "my_second_job"というジョブIDでジョブを定義
  my_second_job:
    name: My second job